# Python Basics

Notebook by:
Romina Piunno \\
Department of Physics \\
University of Toronto \\
Feb. 2021

## Objects

Everything in Python is an "object". Objects can be variables, functions, data structures, etc. What they all have in common is that they each have a uniquie identifier such that they can be referenced in memory. 

In [ ]:
import numpy as np
import random
import time

In [ ]:
# Let's look at a numpy array as an example
a = np.array([[3,1,4,1,5,9], [2,7,1,8,2,8]])
print(a)

[[3 1 4 1 5 9]
 [2 7 1 8 2 8]]


Objects have "attributes" \\
we can access these attributes using a period after the variable name

In [ ]:
# arrays have a shape and size
print(a.shape, a.size)

(2, 6) 12


Objects also have "methods". These are actions that the object knows how to do. \\
We also call methods using a period after the variable name. We can tell the difference between an attribute and a method because methods are always followed by parentheses () which may or may not contain additional arguemnets.

In [ ]:
# arrays can be sorted
a.sort()
print(a)

[[1 1 3 4 5 9]
 [1 2 2 7 8 8]]


In [ ]:
# we can pass an *argument* to sort along a different axis
a.sort(axis=0)
print(a)

[[2 1 1 1 2 8]
 [3 7 4 8 5 9]]


## Lists vs. Dictionaries

Let's say I want to store the phone numbers of all my friends. We need to couple a name to a phone number. There are multiple ways to do this.

In [ ]:
my_friends = ['Elmo', 'Oscar', 'Big Bird', 'Cookie Monster', 'Ernie', 'Bert', 'Grover']
# We can use a list of tuples, or a dictionary for instance
phone_list = []
phone_dict = {}
for friend in my_friends:
  phone_num = random.randint(100,999)
  phone_list.append((friend, phone_num))
  phone_dict[friend] = phone_num

print(phone_list)
print(phone_dict)

[('Elmo', 889), ('Oscar', 141), ('Big Bird', 206), ('Cookie Monster', 682), ('Ernie', 709), ('Bert', 218), ('Grover', 786)]
{'Elmo': 889, 'Oscar': 141, 'Big Bird': 206, 'Cookie Monster': 682, 'Ernie': 709, 'Bert': 218, 'Grover': 786}


In [ ]:
# dictionaries are objects with attributes "keys" and "values"

# keys are used for indexing
print(phone_dict.keys())

# values are what is stored under the key index
print(phone_dict.values())

'''
note: we're calling the keys and values as methods so python returns their
string representation rather than a memory address to where the key and value
objects are kept in memory
'''

dict_keys(['Elmo', 'Oscar', 'Big Bird', 'Cookie Monster', 'Ernie', 'Bert', 'Grover'])
dict_values([889, 141, 206, 682, 709, 218, 786])


"\nnote: we're calling the keys and values as methods so python returns their\nstring representation rather than a memory address to where the key and value\nobjects are kept in memory\n"

In [ ]:
# suppose we want to find Elmo's phone number

# list version
for i in phone_list:
  if i[0] == 'Elmo':
    print("Elmo's phone number:", i[1])


# dictioary version
print("Elmo's phone number:", phone_dict['Elmo'])

Elmo's phone number: 889
Elmo's phone number: 889


Dictionaries are much faster than lists!

In [ ]:
n = 10000000

rand_dict = {}
rand_list = [None] * n # initialize an empty list

for i in range(n):
  num = random.randint(0,n)
  rand_dict[num] = True
  rand_list[i] = num

In [ ]:
test_num = 165164580000
start = time.time()
print(test_num in rand_dict)
end = time.time()
print('Time elapsed:', end - start)

False
Time elapsed: 0.0005965232849121094


In [ ]:
start = time.time()
print(test_num in rand_list)
end = time.time()
print('Time elapsed:', end - start)

False
Time elapsed: 0.11240863800048828


Each obviosly has their place. If you need quick acess to *unsorted* values, use a dictionary. If speed isn't an issue and you want to be able to sort your values, use a list

## A note on lists and pointers

In [ ]:
# let's define a list
a = [1,2,3,4,5]
print(a)

[1, 2, 3, 4, 5]


In [ ]:
# let's say we want another list just like a
b = a
print(b)

[1, 2, 3, 4, 5]


b is a *pointer* to list a. Think of this as a home address to where a lives in memory. If we modify b, it also updates a because it is *pointing* to the same spot in memory.

In [ ]:
b[3] = 7
print(b)
print(a)

[1, 2, 3, 7, 5]
[1, 2, 3, 7, 5]


In [ ]:
# a and b, are both stil pointers to the same place in memory.
# whatever we do to one, also applies to the other
a[3] = 4
print(a)
print(b)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]


If we don't was a pointer to a, but rather a copy that we can modify independently, then we use the following syntax.

In [ ]:
c = a[:]
c[3] = 9
print(c)
print(a)

[1, 2, 3, 9, 5]
[1, 2, 3, 4, 5]
